/**
 * German words for the symbol search: Lucide names its symbols and their words in English only. Lower case, each to
 * the English words of Lucide's names and tags that mean it. A word that is missing only means the English one has to
 * be typed.
 */
export const GERMAN_WORDS: Record<string, string[]> = {
  abfall: ['trash', 'bin'], adresse: ['map-pin', 'address'], akku: ['battery'], alarm: ['alarm'], ampel: ['traffic'],
  anker: ['anchor'], apfel: ['apple'], arbeit: ['briefcase', 'work'], archiv: ['archive'], arzt: ['stethoscope', 'medical'],
  auge: ['eye'], auto: ['car'], bad: ['bath'], bahn: ['train'], ball: ['ball'], bank: ['landmark', 'bank'],
  batterie: ['battery'], baum: ['tree'], baustelle: ['construction', 'hard-hat'], becher: ['cup'], beere: ['cherry'],
  berg: ['mountain'], bett: ['bed'], bewegung: ['activity'], bier: ['beer'], bild: ['image', 'picture'], bilder: ['image', 'images'],
  blatt: ['leaf'], blitz: ['zap', 'lightning'], blume: ['flower'], boot: ['sailboat', 'ship'], brief: ['mail'],
  brille: ['glasses'], brot: ['croissant', 'wheat'], buch: ['book'], buecher: ['book', 'library'], bücher: ['book', 'library'],
  büro: ['briefcase', 'office'], buero: ['briefcase', 'office'], bus: ['bus'], chat: ['message'], code: ['code'],
  computer: ['computer', 'monitor', 'laptop'], dach: ['house'], datei: ['file'], daten: ['database'], datenbank: ['database'],
  diagramm: ['chart'], dokument: ['file-text', 'document'], dollar: ['dollar'], drucker: ['printer'], ei: ['egg'],
  einkauf: ['shopping', 'cart'], einkaufen: ['shopping', 'cart'], eis: ['ice-cream'], eimer: ['bucket'], energie: ['zap', 'energy'],
  erde: ['earth', 'globe'], essen: ['utensils', 'food'], euro: ['euro'], fabrik: ['factory'], fahrrad: ['bike', 'bicycle'],
  fahne: ['flag'], familie: ['users', 'family'], farbe: ['palette', 'paint'], feder: ['feather'], fenster: ['app-window', 'window'],
  fernseher: ['tv'], feuer: ['flame', 'fire'], film: ['film', 'clapperboard'], finanzen: ['wallet', 'finance'], fisch: ['fish'],
  flagge: ['flag'], flasche: ['bottle'], flugzeug: ['plane'], foto: ['camera', 'image'], frage: ['help', 'question'],
  freunde: ['users', 'friends'], frucht: ['apple', 'fruit'], fuss: ['footprints'], fuß: ['footprints'], garten: ['sprout', 'flower', 'garden'],
  gebäude: ['building'], gebaeude: ['building'], geburtstag: ['cake', 'party'], geld: ['wallet', 'banknote', 'coins', 'money'],
  gemüse: ['carrot', 'salad', 'vegetable'], gemuese: ['carrot', 'salad', 'vegetable'], geschenk: ['gift'], gesundheit: ['heart-pulse', 'health'],
  getränk: ['cup', 'drink'], getraenk: ['cup', 'drink'], gitarre: ['guitar'], glas: ['wine', 'glass'], glocke: ['bell'],
  glühbirne: ['lightbulb'], gluehbirne: ['lightbulb'], hammer: ['hammer'], hand: ['hand'], handy: ['smartphone', 'phone'],
  haus: ['house', 'home'], heim: ['house', 'home'], herz: ['heart'], himmel: ['cloud', 'sky'], hund: ['dog'], hut: ['hat'],
  idee: ['lightbulb', 'idea'], information: ['info'], insel: ['palmtree', 'island'], internet: ['globe', 'wifi'], jahr: ['calendar'],
  kaffee: ['coffee'], kalender: ['calendar'], kamera: ['camera'], karte: ['map'], kasse: ['receipt', 'register'], katze: ['cat'],
  kerze: ['flame', 'candle'], kette: ['link'], kind: ['baby', 'child'], kinder: ['baby', 'child'], kirche: ['church'], kiste: ['box', 'package'],
  klavier: ['piano'], kleidung: ['shirt'], koffer: ['luggage', 'briefcase'], kopfhörer: ['headphones'], kopfhoerer: ['headphones'],
  krankenhaus: ['hospital'], kreis: ['circle'], kreuz: ['cross', 'x'], krone: ['crown'], küche: ['chef-hat', 'cooking-pot', 'utensils', 'kitchen'],
  kueche: ['chef-hat', 'cooking-pot', 'utensils', 'kitchen'], kuchen: ['cake'], kunst: ['palette', 'brush', 'art'], lager: ['warehouse'],
  lampe: ['lamp', 'lightbulb'], land: ['flag', 'globe'], laptop: ['laptop'], laub: ['leaf'], lautsprecher: ['speaker', 'volume'],
  lebensmittel: ['apple', 'carrot', 'food'], lernen: ['graduation-cap', 'book', 'school'], lesezeichen: ['bookmark'], licht: ['lightbulb', 'sun'],
  liebe: ['heart'], liste: ['list'], mail: ['mail'], mann: ['user'], medizin: ['pill', 'medical'], meer: ['waves', 'sea'],
  mensch: ['user', 'person'], menschen: ['users', 'people'], messer: ['knife'], mond: ['moon'], motorrad: ['bike', 'motorbike'],
  musik: ['music'], nachricht: ['message', 'mail'], natur: ['leaf', 'trees', 'nature'], netz: ['network', 'wifi'], netzwerk: ['network'],
  notiz: ['notebook', 'sticky-note', 'note'], notizen: ['notebook', 'sticky-note', 'note'], ordner: ['folder'], ort: ['map-pin'], paket: ['package'],
  papier: ['file', 'paper'], party: ['party-popper'], pferd: ['horse'], pflanze: ['sprout', 'plant'], pizza: ['pizza'], planet: ['orbit', 'planet'],
  post: ['mail', 'mailbox'], projekt: ['folder-kanban', 'project'], projekte: ['folder-kanban', 'project'], puzzle: ['puzzle'],
  rad: ['bike', 'wheel'], rakete: ['rocket'], rechnung: ['receipt', 'invoice'], regen: ['cloud-rain', 'rain'], reise: ['plane', 'luggage', 'travel'],
  reisen: ['plane', 'luggage', 'travel'], rezept: ['chef-hat', 'receipt'], rezepte: ['chef-hat'], ring: ['ring'], rucksack: ['backpack'],
  säge: ['saw'], saege: ['saw'], schach: ['chess'], schaf: ['sheep'], schiff: ['ship'], schild: ['shield', 'sign'], schlafen: ['bed', 'moon'],
  schloss: ['lock', 'castle'], schlüssel: ['key'], schluessel: ['key'], schmetterling: ['butterfly'], schnee: ['snowflake'], schraube: ['wrench', 'screw'],
  schreiben: ['pen', 'pencil'], schule: ['school', 'graduation-cap'], schwein: ['piggy-bank'], see: ['waves'], server: ['server'],
  sicherheit: ['shield', 'lock'], sicherung: ['archive', 'hard-drive', 'backup'], sonne: ['sun'], spiel: ['gamepad', 'dice', 'game'],
  spiele: ['gamepad', 'dice', 'game'], sport: ['dumbbell', 'trophy', 'sport'], sprache: ['languages', 'speech'], stadt: ['building', 'city'],
  stern: ['star'], stift: ['pen', 'pencil'], strand: ['palmtree', 'beach'], straße: ['road'], strasse: ['road'], strom: ['plug', 'zap', 'power'],
  stuhl: ['armchair', 'chair'], suche: ['search'], tabelle: ['table', 'sheet'], tag: ['calendar', 'sun'], tasche: ['bag'], tastatur: ['keyboard'],
  team: ['users'], technik: ['cpu', 'settings', 'wrench'], telefon: ['phone'], termin: ['calendar-clock', 'calendar'], text: ['text', 'type'],
  tier: ['paw', 'animal'], tiere: ['paw', 'animal'], tisch: ['table'], tor: ['goal'], trinken: ['cup', 'glass', 'drink'], tür: ['door'],
  tuer: ['door'], uhr: ['clock', 'watch'], umwelt: ['leaf', 'recycle'], universität: ['graduation-cap', 'university'], urlaub: ['palmtree', 'plane', 'luggage'],
  vogel: ['bird'], wald: ['trees', 'forest'], waage: ['scale'], wagen: ['car'], wasser: ['droplet', 'water'], wecker: ['alarm-clock'],
  welt: ['globe', 'earth'], werkstatt: ['wrench', 'hammer', 'tool'], werkzeug: ['wrench', 'hammer', 'tool'], wetter: ['cloud-sun', 'weather'],
  wissen: ['brain', 'book', 'library'], wissenschaft: ['flask', 'atom', 'science'], wlan: ['wifi'], wohnung: ['house', 'building'],
  wolke: ['cloud'], wurst: ['beef'], zahl: ['hash'], zahn: ['tooth'], zeit: ['clock', 'timer', 'time'], zeitung: ['newspaper'],
  zelt: ['tent'], ziel: ['target', 'goal'], zimmer: ['bed', 'door'], zug: ['train'], zuhause: ['house', 'home'],
}
